FROM stabletec/build-core:ubuntu

RUN apt install -y \
    glslang-tools \
    libassimp-dev \
    libvulkan-dev \
    libglfw3-dev \
    libglm-dev \
    libfmt-dev  \
    libyaml-cpp-dev \
    && apt clean all
